import { ProjectsSectionType } from '@/lib/types/sections';
import { getId } from '@/lib/utils/helper';

export const projectsSection: ProjectsSectionType = {
  title: 'my achievements',
  projects: [
    {
      id: getId(),
      name: 'Conrad Innovator — NASA Conrad Challenge Global Finalist',
      url: '#',
      repo: '#',
      img: 'https://images.unsplash.com/photo-1581092334700-7d89c0e8fa61',
      year: 2024,
      tags: ['Global Finalist', 'Innovation', 'NASA Conrad'],
    },
    {
      id: getId(),
      name: '6th RC National Science Fest — National Champion',
      url: '#',
      repo: '#',
      img: 'https://images.unsplash.com/photo-1518770660439-4636190af475',
      year: 2023,
      tags: ['National Champion', 'Science Fest'],
    },
    {
      id: getId(),
      name: 'BCSIR National Science & Tech Fair — Regional & National Winner',
      url: '#',
      repo: '#',
      img: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085',
      year: 2023,
      tags: ['BCSIR', 'National Winner'],
    },
    {
      id: getId(),
      name: 'SMC MODINMIXPLUS Khude Bigyani Award — National Award',
      url: '#',
      repo: '#',
      img: 'https://images.unsplash.com/photo-1485820575493-1ea61ed3538e',
      year: 2023,
      tags: ['National Award', 'Khude Bigyani'],
    },
    {
      id: getId(),
      name: 'Beyond The Metrics — IUT — National Round Winner',
      url: '#',
      repo: '#',
      img: 'https://images.unsplash.com/photo-1527430253228-e43f4e0bcbf5',
      year: 2023,
      tags: ['IUT', 'National Round Winner'],
    },
    {
      id: getId(),
      name: 'bKash-Biggan Chinta Biggan Utsob — Regional Champion',
      url: '#',
      repo: '#',
      img: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b',
      year: 2022,
      tags: ['Regional Champion', 'Science Fair'],
    },
    {
      id: getId(),
      name: 'District Level Champion — 44th & 45th Science & Tech Fair',
      url: '#',
      repo: '#',
      img: 'https://images.unsplash.com/photo-1605902711622-cfb43c44367b',
      year: 2023,
      tags: ['District Champion', 'Science & Tech Fair'],
    },
  ],
};
